config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show] do
    resources :dailies
  end


  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily.rb
class Daily < ActiveRecord::Base
  validates :goal, presence: true
  belongs_to :user
  has_many :scores


  def past_week
    self.scores.where('date >= ?', 1.week.ago)
  end

end

app/models/score.rb
class Score < ActiveRecord::Base
  before_create :set_default_date

  validates :score, presence: true
  # validates :date, uniqueness: true
  belongs_to :daily


  def set_default_date
    self.date = Date.today unless self.date
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness: true
  validates :email, uniqueness: true
  has_many :dailies
  has_secure_password

  enum role: %w(default admin)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dailies_controller.rb
class DailiesController < ApplicationController

  def new
    @user = User.find(params[:user_id])
    @daily = Daily.new
    # 6.times do
      # @dailies << Daily.new
    # end
  end

  def create
    @daily = Daily.new(daily_params)
    @daily.save
    # binding.pry
    flash[:success] = "Goal Added"
    redirect_to user_path(params[:user_id])
  end

  def show
    @daily = Daily.find(params[:id])
  end

  def edit
    @daily = Daily.find(params[:id])
    @user = @daily.user
  end

  def update
    @daily = Daily.find(params[:id])
    @daily.update(daily_params)
    redirect_to user_daily_path(@daily)
  end




  def destroy
    # binding.pry
    @daily = Daily.find(params[:id])
    user = @daily.user
    @daily.destroy
    flash[:deleted] = "Goal Deleted"
    redirect_to user
  end



  private

  def daily_params
    params.require(:daily).permit(:goal, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end




  def create
    # binding.pry
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Login Successful"
      redirect_to user_path(user)
    else
      flash.now[:failure] = "Login Unsuccessful"
      render :new
    end
    # username: params[:session][:username]

  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Account Created"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:failure] = "Please fill out all fields"
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dailies/_form.html.erb
<%= form_for [@user, @daily] do |f| %>
  <%= f.label :goal %>
  <%= f.text_field :goal %>
  <%= f.hidden_field :user_id, value: @user.id %>
  <%= f.submit %>
<% end %>

app/views/dailies/edit.html.erb
<%= render partial: "form" %>

app/views/dailies/new.html.erb
<%= render partial: "form" %>

app/views/dailies/show.html.erb
<%= @daily.goal %>

<% @daily.scores.each do |score| %>
  <div class="score">
    Date: <%= score.date %>
    Score: <%= score.score %>
  </div>
<% end %>
<%= link_to "Edit Goal", edit_user_daily_path(@daily) %>
<%= link_to "Delete Goal", user_daily_path(@daily), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DailyGoals</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% flash.each do |type, message| %>
    <%= content_tag :div, message, class: "flash_#{type}" %>
  <% end %>


    <%= yield %>


  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :email%>
  <%= f.text_field :email%>
  <%= f.label :password%>
  <%= f.password_field :password%>
  <%= f.submit %>

<% end%>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username %></h1>

  <div class="dailies">
    <% @user.dailies.each do |daily| %>
    <div class="daily">
      <%= link_to daily.goal, user_daily_path(@user, daily) %>
    </div>
    <% end %>
 </div>

<%= link_to "Create Dailies", new_user_daily_path(@user) %>